// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYKM6F5bDoPUS2VzhhpRh5sKU6IA43bz0',
    appId: '1:618812622213:web:679d382de8864014a970ec',
    messagingSenderId: '618812622213',
    projectId: 'campus-updates',
    authDomain: 'campus-updates.firebaseapp.com',
    databaseURL: 'https://campus-updates-default-rtdb.firebaseio.com',
    storageBucket: 'campus-updates.firebasestorage.app',
    measurementId: 'G-ECLRKC5LPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASut20xyhi0reUOQcLG4R_TkdlgZ6TNGw',
    appId: '1:618812622213:android:1d091ca4e4a739fba970ec',
    messagingSenderId: '618812622213',
    projectId: 'campus-updates',
    databaseURL: 'https://campus-updates-default-rtdb.firebaseio.com',
    storageBucket: 'campus-updates.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYKM6F5bDoPUS2VzhhpRh5sKU6IA43bz0',
    appId: '1:618812622213:web:c7e16624af2d9326a970ec',
    messagingSenderId: '618812622213',
    projectId: 'campus-updates',
    authDomain: 'campus-updates.firebaseapp.com',
    databaseURL: 'https://campus-updates-default-rtdb.firebaseio.com',
    storageBucket: 'campus-updates.firebasestorage.app',
    measurementId: 'G-19SDGNGCZD',
  );

}